FROM node:alpine as build

WORKDIR "/home/app"

RUN npm install -g pm2

COPY package.json .
RUN npm install

COPY . .
RUN npm run build

EXPOSE 3000

CMD [ "pm2-runtime", "npm", "--", "start", "--", "-p", "3000"]