name: Test simplenext

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the docker image
        run: docker build . --file Dockerfile.dev --tag samueladekunle/simplenext-dev:latest


  lint:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the docker image
        run: docker build . --file Dockerfile.dev --tag samueladekunle/simplenext-dev:latest

      - name: Run the jest tests
        run: docker run samueladekunle/simplenext-dev:latest npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the docker image
        run: docker build . --file Dockerfile.dev --tag samueladekunle/simplenext-dev:latest

      - name: Run the jest tests
        run: docker run samueladekunle/simplenext-dev:latest npm run test -- --coverage